<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CreateCountryTable extends Migration
{
    public function up(): void
    {
        $this->forge->addField([
            'id'        => ['type' => 'INT', 'unsigned' => true, 'auto_increment' => true],
            'name'      => ['type' => 'VARCHAR', 'constraint' => 100],
            'phonecode' => ['type' => 'VARCHAR', 'constraint' => 10],
        ]);
        $this->forge->addPrimaryKey('id');
        $this->forge->createTable('tbl_country', true);

        $db = \Config\Database::connect();
        $db->table('tbl_country')->insertBatch([
            ['name' => 'Afghanistan', 'phonecode' => '93'],
            ['name' => 'Albania', 'phonecode' => '355'],
            ['name' => 'Algeria', 'phonecode' => '213'],
            ['name' => 'Andorra', 'phonecode' => '376'],
            ['name' => 'Angola', 'phonecode' => '244'],
            ['name' => 'Argentina', 'phonecode' => '54'],
            ['name' => 'Armenia', 'phonecode' => '374'],
            ['name' => 'Australia', 'phonecode' => '61'],
            ['name' => 'Austria', 'phonecode' => '43'],
            ['name' => 'Azerbaijan', 'phonecode' => '994'],
            ['name' => 'Bahrain', 'phonecode' => '973'],
            ['name' => 'Bangladesh', 'phonecode' => '880'],
            ['name' => 'Belarus', 'phonecode' => '375'],
            ['name' => 'Belgium', 'phonecode' => '32'],
            ['name' => 'Belize', 'phonecode' => '501'],
            ['name' => 'Bolivia', 'phonecode' => '591'],
            ['name' => 'Bosnia and Herzegovina', 'phonecode' => '387'],
            ['name' => 'Brazil', 'phonecode' => '55'],
            ['name' => 'Brunei', 'phonecode' => '673'],
            ['name' => 'Bulgaria', 'phonecode' => '359'],
            ['name' => 'Cambodia', 'phonecode' => '855'],
            ['name' => 'Cameroon', 'phonecode' => '237'],
            ['name' => 'Canada', 'phonecode' => '1'],
            ['name' => 'Chile', 'phonecode' => '56'],
            ['name' => 'China', 'phonecode' => '86'],
            ['name' => 'Colombia', 'phonecode' => '57'],
            ['name' => 'Costa Rica', 'phonecode' => '506'],
            ['name' => 'Croatia', 'phonecode' => '385'],
            ['name' => 'Cuba', 'phonecode' => '53'],
            ['name' => 'Cyprus', 'phonecode' => '357'],
            ['name' => 'Czech Republic', 'phonecode' => '420'],
            ['name' => 'Denmark', 'phonecode' => '45'],
            ['name' => 'Dominican Republic', 'phonecode' => '1'],
            ['name' => 'Ecuador', 'phonecode' => '593'],
            ['name' => 'Egypt', 'phonecode' => '20'],
            ['name' => 'Ethiopia', 'phonecode' => '251'],
            ['name' => 'Finland', 'phonecode' => '358'],
            ['name' => 'France', 'phonecode' => '33'],
            ['name' => 'Georgia', 'phonecode' => '995'],
            ['name' => 'Germany', 'phonecode' => '49'],
            ['name' => 'Ghana', 'phonecode' => '233'],
            ['name' => 'Greece', 'phonecode' => '30'],
            ['name' => 'Guatemala', 'phonecode' => '502'],
            ['name' => 'Honduras', 'phonecode' => '504'],
            ['name' => 'Hong Kong', 'phonecode' => '852'],
            ['name' => 'Hungary', 'phonecode' => '36'],
            ['name' => 'Iceland', 'phonecode' => '354'],
            ['name' => 'India', 'phonecode' => '91'],
            ['name' => 'Indonesia', 'phonecode' => '62'],
            ['name' => 'Iran', 'phonecode' => '98'],
            ['name' => 'Iraq', 'phonecode' => '964'],
            ['name' => 'Ireland', 'phonecode' => '353'],
            ['name' => 'Israel', 'phonecode' => '972'],
            ['name' => 'Italy', 'phonecode' => '39'],
            ['name' => 'Jamaica', 'phonecode' => '1'],
            ['name' => 'Japan', 'phonecode' => '81'],
            ['name' => 'Jordan', 'phonecode' => '962'],
            ['name' => 'Kazakhstan', 'phonecode' => '7'],
            ['name' => 'Kenya', 'phonecode' => '254'],
            ['name' => 'Kuwait', 'phonecode' => '965'],
            ['name' => 'Kyrgyzstan', 'phonecode' => '996'],
            ['name' => 'Laos', 'phonecode' => '856'],
            ['name' => 'Latvia', 'phonecode' => '371'],
            ['name' => 'Lebanon', 'phonecode' => '961'],
            ['name' => 'Libya', 'phonecode' => '218'],
            ['name' => 'Lithuania', 'phonecode' => '370'],
            ['name' => 'Luxembourg', 'phonecode' => '352'],
            ['name' => 'Malaysia', 'phonecode' => '60'],
            ['name' => 'Maldives', 'phonecode' => '960'],
            ['name' => 'Malta', 'phonecode' => '356'],
            ['name' => 'Mexico', 'phonecode' => '52'],
            ['name' => 'Moldova', 'phonecode' => '373'],
            ['name' => 'Monaco', 'phonecode' => '377'],
            ['name' => 'Mongolia', 'phonecode' => '976'],
            ['name' => 'Morocco', 'phonecode' => '212'],
            ['name' => 'Myanmar', 'phonecode' => '95'],
            ['name' => 'Namibia', 'phonecode' => '264'],
            ['name' => 'Nepal', 'phonecode' => '977'],
            ['name' => 'Netherlands', 'phonecode' => '31'],
            ['name' => 'New Zealand', 'phonecode' => '64'],
            ['name' => 'Nicaragua', 'phonecode' => '505'],
            ['name' => 'Nigeria', 'phonecode' => '234'],
            ['name' => 'North Korea', 'phonecode' => '850'],
            ['name' => 'Norway', 'phonecode' => '47'],
            ['name' => 'Oman', 'phonecode' => '968'],
            ['name' => 'Pakistan', 'phonecode' => '92'],
            ['name' => 'Palestine', 'phonecode' => '970'],
            ['name' => 'Panama', 'phonecode' => '507'],
            ['name' => 'Paraguay', 'phonecode' => '595'],
            ['name' => 'Peru', 'phonecode' => '51'],
            ['name' => 'Philippines', 'phonecode' => '63'],
            ['name' => 'Poland', 'phonecode' => '48'],
            ['name' => 'Portugal', 'phonecode' => '351'],
            ['name' => 'Qatar', 'phonecode' => '974'],
            ['name' => 'Romania', 'phonecode' => '40'],
            ['name' => 'Russia', 'phonecode' => '7'],
            ['name' => 'Saudi Arabia', 'phonecode' => '966'],
            ['name' => 'Senegal', 'phonecode' => '221'],
            ['name' => 'Serbia', 'phonecode' => '381'],
            ['name' => 'Singapore', 'phonecode' => '65'],
            ['name' => 'Slovakia', 'phonecode' => '421'],
            ['name' => 'Slovenia', 'phonecode' => '386'],
            ['name' => 'Somalia', 'phonecode' => '252'],
            ['name' => 'South Africa', 'phonecode' => '27'],
            ['name' => 'South Korea', 'phonecode' => '82'],
            ['name' => 'Spain', 'phonecode' => '34'],
            ['name' => 'Sri Lanka', 'phonecode' => '94'],
            ['name' => 'Sudan', 'phonecode' => '249'],
            ['name' => 'Sweden', 'phonecode' => '46'],
            ['name' => 'Switzerland', 'phonecode' => '41'],
            ['name' => 'Syria', 'phonecode' => '963'],
            ['name' => 'Taiwan', 'phonecode' => '886'],
            ['name' => 'Tajikistan', 'phonecode' => '992'],
            ['name' => 'Tanzania', 'phonecode' => '255'],
            ['name' => 'Thailand', 'phonecode' => '66'],
            ['name' => 'Tunisia', 'phonecode' => '216'],
            ['name' => 'Turkey', 'phonecode' => '90'],
            ['name' => 'Turkmenistan', 'phonecode' => '993'],
            ['name' => 'Uganda', 'phonecode' => '256'],
            ['name' => 'Ukraine', 'phonecode' => '380'],
            ['name' => 'United Arab Emirates', 'phonecode' => '971'],
            ['name' => 'United Kingdom', 'phonecode' => '44'],
            ['name' => 'United States', 'phonecode' => '1'],
            ['name' => 'Uruguay', 'phonecode' => '598'],
            ['name' => 'Uzbekistan', 'phonecode' => '998'],
            ['name' => 'Venezuela', 'phonecode' => '58'],
            ['name' => 'Vietnam', 'phonecode' => '84'],
            ['name' => 'Yemen', 'phonecode' => '967'],
            ['name' => 'Zimbabwe', 'phonecode' => '263'],
        ]);
    }

    public function down(): void
    {
        $this->forge->dropTable('tbl_country', true);
    }
}
